dist: xenial
language: minimal
addons:
    apt:
      packages:
        - qemu
        - qemu-user-static
        - binfmt-support
services:
    - docker
env:
    - NODE_VERSION=arm32v7/node:10-buster
    - NODE_VERSION=arm32v7/node:12-buster
    - NODE_VERSION=arm64v8/node:10-buster
    - NODE_VERSION=arm64v8/node:12-buster
install: skip
#before_script: docker run --rm --privileged multiarch/qemu-user-static:register
script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset 
    - ./docker_build.sh $NODE_VERSION
